project_id = "dbgxuneppeupwfcrsbli"

[functions.auth-instagram]
verify_jwt = false

[functions.fetch-instagram-data]
verify_jwt = false

[functions.auth-youtube]
verify_jwt = false

[functions.auth-google-analytics]
verify_jwt = false