project_id = "arlnboevgndtpnprolhz"

[functions.auth-instagram]
verify_jwt = false

[functions.fetch-instagram-data]
verify_jwt = false

[functions.auth-youtube]
verify_jwt = false

[functions.auth-google-analytics]
verify_jwt = false

[functions.auth-facebook]
verify_jwt = false

[functions.auth-linkedin]
verify_jwt = false

[functions.fetch-youtube-data]
verify_jwt = false

[functions.fetch-google-analytics-data]
verify_jwt = false

[functions.fetch-facebook-data]
verify_jwt = false

[functions.fetch-linkedin-data]
verify_jwt = false
